config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/:id' => 'users#show', as: 'user'
  match 'users/:id' => 'users#destroy', via: :delete, as: :admin_destroy_user
  match 'users/:id/rise_to_admin' => 'users#rise_to_admin', via: :get, as: :rise_to_admin_user
  get 'users', to: 'users#index'

  resources :tutorials do
    resources :tutorial_grades, only: [:create]
    resources :tutorial_comments, path: 'comments', only: [:create,:update,:destroy] do
      resources :tutorial_comment_votes, only: [:create,:update,:destroy]
    end
    resources :parts do
      get 'up_position', on: :member
      get 'down_position', on: :member
      get 'execute', on: :member
      resources :part_votes,only: [:create,:update,:destroy]
      resources :done_parts,only: [:create,:destroy]
      resources :part_comments, path: 'comments', only: [:index,:create,:update,:destroy] do
        resources :part_comment_votes, only: [:create,:update,:destroy]
      end
    end
  end

  resources :interpreters do
    resources :interpreter_grades, only: [:create]
    resources :interpreter_comments, path: 'comments', only: [:create,:update,:destroy] do
      resources :interpreter_comment_votes, only: [:create,:update,:destroy]
    end
    resources :functions do
      get 'up_position', on: :member
      get 'down_position', on: :member
      resources :function_votes,only: [:create,:update,:destroy]
      resources :function_comments, path: 'comments', only: [:index,:create,:update,:destroy] do
        resources :function_comment_votes, only: [:create,:update,:destroy]
      end
    end
  end

  get '/home' => 'page#home'
  get '/creator' => 'page#creator'
  get '/about' => 'page#about'

  root 'page#home'

end

app/models/interpreter.rb
class Interpreter < ActiveRecord::Base
  has_many :interpreter_comments, inverse_of: :interpreter, dependent: :delete_all
  has_many :interpreter_grades, inverse_of: :interpreter, dependent: :delete_all
  has_many :functions, inverse_of: :interpreter, dependent: :delete_all
  has_many :tutorials, inverse_of: :interpreter
  belongs_to :user

  validates :title,:description, :open_token, :close_token, :user, presence: true
  validates :is_finish, inclusion: [true, false]
  validates :open_token, length: { is: 1 }
  validates :close_token, length: { is: 1 }

  def grade_mean
    return 0.0 if self.interpreter_grades.count == 0
    self.interpreter_grades.sum(:grade) / self.interpreter_grades.count
  end

  def functions_ordered
    self.functions.order(position: :asc)
  end

  def comments_top
    self.interpreter_comments.sort_by{|e| e.votes.where(positive: false).count-e.votes.where(positive: true).count}
  end
end

app/controllers/interpreters_controller.rb
class InterpretersController < ApplicationController

  before_action :authenticate_creator!, except: [:show,:new,:create]
  before_action :authenticate_user!, only: [:new,:create]

  def show
    @interpreter = Interpreter.find(params[:id])
    @functions = @interpreter.functions_ordered
    @comment = InterpreterComment.new
    @comments = @interpreter.comments_top.paginate(page: params[:page], per_page: COMMENTS_PER_PAGE)

    @grade = @interpreter.interpreter_grades.where(user_id: current_user.id).first.grade rescue nil
    @grade = 0.0 if @grade.blank?
  end

  def create
    @interpreter = Interpreter.new(interpreter_params)

    @interpreter.version = 1
    @interpreter.user = current_user
    @interpreter.is_finish = false if params[:is_finish].blank?

    if @interpreter.save
      redirect_to [:edit,@interpreter]
    else
      render 'new'
    end
  end

  def new
    @interpreter = Interpreter.new
  end

  def update
    @interpreter = Interpreter.find(params[:id])

    @interpreter.version = @interpreter.version+1

    if @interpreter.update(interpreter_params)
      redirect_to @interpreter
    else
      render 'edit'
    end
  end

  def edit
    @interpreter = Interpreter.find(params[:id])
    @functions = @interpreter.functions_ordered
    @function = Function.new
  end

  def destroy
    Interpreter.find(params[:id]).destroy
    redirect_to root_path, flash: { info: 'Interpreter deleted' }
  end

  private
  def authenticate_creator!
    interpreter = Interpreter.find(params[:id])
    redirect_to root_path unless interpreter.user == current_user || admin?
  end

  def interpreter_params
    params.require(:interpreter).permit(:title, :description, :is_finish, :open_token, :close_token, :version)
  end
end

app/helpers/interpreters_helper.rb
module InterpretersHelper

end

app/views/interpreters/_function_form.html.erb
<%= form_for link, namespace: link.last.id do |f| %>

  <div class="row">
    <% if new %>
      <div class="large-9 columns">
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: 'Name of your function without space, e.g. "my_function"' %>
      </div>
    <% else %>
      <div class="large-1 text-center columns">
        <%= link_to '', up_position_interpreter_function_path(link.first, id: link.last.id.to_s),class: 'arrow-up', method: :get %><br><br>
        <%= link_to '', down_position_interpreter_function_path(link.first, id: link.last.id.to_s),class: 'arrow-down', method: :get %>

      </div>
      <div class="large-8 columns">
        <%= f.label :title %>
        <%= f.text_field :title, autocomplete: true  %>
      </div>

    <% end %>

    <div class="large-1 columns">
      <%= f.label :loop %>
      <%= f.check_box :loop, autocomplete: true  %>
    </div>

    <div class="large-2 columns">
      <%= f.label :signature %>
      <!--set default value for new function-->
      <%= f.check_box :signature, autocomplete: true unless new%>
      <%= f.check_box :signature, autocomplete: true, checked: true if new%>
    </div>

  </div>
  <div class="row">
    <div class="large-12 columns">
      <%= f.label :description,'Description of your function (what is it doing)' %>
      <%= f.text_area :description, namespace: link.last.id, class: 'tinymce', rows: 15, autocomplete: true  %>
    </div>
  </div>
  <div class="row">
    <div class="large-6 columns">
      <%= f.label :regex, 'Regex to find the line' %>
      <%= f.text_area :regex, autocomplete: true  %>
    </div>
    <div class="large-6 columns">
      <label>Regex tester (optional)</label>
      <textarea onkeyup="regexTester(this, '<%= link.last.id.to_s+'_' unless link.last.id.blank?  %>function_regex')"> </textarea>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <%= f.label :content, 'Content (ruby code which will be executed when the parser find a line which match with your regex)' %>
      <%= f.text_area :content, namespace: link.last.id.to_s, size: '1x15', autocomplete: true %>
    </div>
  </div>
  <div class="row">
    <div class="large-6 columns">
      <%= f.submit class: 'button tiny' %>
    </div>
    <div class="large-6 columns">
      <% unless new %>
        <%= link_to 'delete', link, method: :delete, class: 'button tiny alert right' %>
        <%= link_to 'Go to the page', link, class: 'button tiny right' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/interpreters/_help_interpreter.html.erb
<dl class="accordion" data-accordion>
  <dd>
    <a href="#help_section">Help (how it's works)</a>

    <div id="help_section" class="content">
      <ol>
        <li>Choose a name of the function that doesn't contain spaces.</li>
        <li>Add a description which summarize what the function do.</li>
        <li>Choose if your function will be a loop or not</li>
        <li>Choose if you want the function to be in the code comparison</li>
        <li>
          Find a regex which will match with your line. The most precise it is the best it is.<br>
          In the case where the regex is small and cover a large possibilities,<br>
          put this functions at the end of order list.
        </li>
        <li>
          The content of the function is ruby code.<br>
          If it's isn't a condition, it must return true.<br>
          <ul class="no-bullet">
            <li><b>Actual line :</b>
              <ul class="no-bullet">
                <li><kbd>line</kbd> Is a variable which contain the actual line.</li>
              </ul>
            </li>
            <li><b>Variables :</b>
              <ul class="no-bullet">
                <li>instantiate : <kbd>Variable.new(variable_name,variable_value.to_f)</kbd></li>
                <li>find variable : <kbd>Variable.convert(a_variable_name)</kbd></li>
              </ul>
            </li>
            <li><b>Output :</b>
              <ul class="no-bullet">
                <li>Add values to the output you must use this : <kbd>LIFunction.output("something")</kbd></li>
              </ul>
            </li>
          </ul>
        </li>
      </ol>
      <h5><b>C interpreter example</b></h5>
      <dl class="tabs small" data-tab>
        <dd class="active"><a href="#panel2-1">Initial variables</a></dd>
        <dd><a href="#panel2-2">Printf function</a></dd>
        <dd><a href="#panel2-3">If statement</a></dd>
        <dd><a href="#panel2-4">While loop</a></dd>
        <dd><a href="#panel2-5">Empty lines</a></dd>
      </dl>
      <div class="tabs-content">
        <div class="content active" id="panel2-1">
          <b>Name : </b><kbd>init_vars_func</kbd><br>
          <b>Regex : </b><kbd>\w+ *= *\d+</kbd><br>
          <b>Content : </b><br>
<pre>variable_name = line.scan(/\w+/)[1]
variable_value = line.scan(/\w+/)[2]
LIVariable.new(variable_name,variable_value.to_f)
next Thread.current[:return] = true</pre>
        </div>
        <div class="content" id="panel2-2">
          <b>Name : </b><kbd>printf_func</kbd><br>
          <b>Regex : </b><kbd>printf *\(['"].*["']\) *;</kbd><br>
          <b>Content : </b><br>
<pre>line = line[/[\"](.*?)[\"]/]
LIFunction.output(line[1..-2])
next Thread.current[:return] = true</pre>
        </div>
        <div class="content" id="panel2-3">
          <b>Name : </b><kbd>if_statement</kbd><br>
          <b>Regex : </b><kbd>if *\( *\w+ *[<>=]=? *\w+ *\)</kbd><br>
          <b>Content : </b><br>
<pre>operator = line.scan(/[<>=]=?/)[0]
numbers = line.scan(/\w+/)[1,3] # remove the if and get only numbers or vars

numbers[0] = numbers[0].to_f if numbers[0] =~ /\d+/
numbers[1] = numbers[1].to_f if numbers[1] =~ /\d+/

# if it\'s variable names, then change it to get the real variable
if numbers[0].is_a? String #should change but for the moment still use this work around
  numbers[0] = LIVariable.convert numbers[0]
end
if numbers[1].is_a? String #should change but for the moment still use this work around
  numbers[1] = LIVariable.convert numbers[1]
end

next Thread.current[:return] = numbers[0] >= numbers[1] if operator == '>='
next Thread.current[:return] = numbers[0] <  numbers[1] if operator == '<'
next Thread.current[:return] = numbers[0] <= numbers[1] if operator == '<='
next Thread.current[:return] = numbers[0] == numbers[1] if operator == '=='
next Thread.current[:return] = numbers[0] >  numbers[1] if operator == '>'</pre>
        </div>
        <div class="content" id="panel2-4">
          <b>Name : </b><kbd>while_func</kbd><br>
          <b>Regex : </b><kbd>while *\( *\w+ *[<>=]=? *\w+ *\)</kbd><br>
          <b>Content : </b><br>
<pre>operator = line.scan(/[<>=]=?/)[0]
numbers = line.scan(/\w+/)[1,3]

numbers[0] = numbers[0].to_f if numbers[0] =~ /\d+/
numbers[1] = numbers[1].to_f if numbers[1] =~ /\d+/

# if it's variable names, then change it to get the real variable
if numbers[0].is_a? String #should change but for the moment still use this work around
  numbers[0] = LIVariable.convert numbers[0]
end
if numbers[1].is_a? String #should change but for the moment still use this work around
  numbers[1] = LIVariable.convert numbers[1]
end

next Thread.current[:return] = numbers[0] >= numbers[1] if operator == '>='
next Thread.current[:return] = numbers[0] <  numbers[1] if operator == '<'
next Thread.current[:return] = numbers[0] <= numbers[1] if operator == '<='
next Thread.current[:return] = numbers[0] == numbers[1] if operator == '=='
next Thread.current[:return] = numbers[0] >  numbers[1] if operator == '>'</pre>
        </div>
        <div class="content" id="panel2-5">
          <b>Name : </b><kbd>nothing_func</kbd><br>
          <b>Regex : </b><kbd>^ *\t?\r?\n$</kbd><br>
          <b>Content : </b><br>
<pre>next Thread.current[:return] = true</pre>
        </div>
      </div>
    </div>
  </dd>
</dl>

app/views/interpreters/_interpreter_form.html.erb
<div class="row">
  <div class="large-12 columns">
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: 'A classic title would be "C"'%>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'tinymce', rows: 15 %>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <%= form.label :is_finish %>
    <%= form.check_box :is_finish %>
  </div>
</div>

<div class="row">
  <div class="large-6 columns">
    <%= form.label :open_token, 'Token to open a block' %>
    <%= form.text_field :open_token, placeholder: 'In C language it is {', maxlength: '1'%>
  </div>

  <div class="large-6 columns">
    <%= form.label :close_token, 'Token to end a block' %>
    <%= form.text_field :close_token,placeholder: 'In C language it is }', maxlength: '1' %>
  </div>
</div>

app/views/interpreters/edit.html.erb
<%= breadcrumbs({title: @interpreter.title, link: @interpreter}, current: 'edit') %>
<%= tinymce_assets %>
<%= tinymce %>

<%= render partial: 'layouts/delete_confirm', locals: {id: 'interpreterDelete', name: 'interpreter', link: @interpreter}%>

<%= form_for :interpreter, url: interpreter_path(@interpreter), method: :patch do |f| %>
  <% if @interpreter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interpreter.errors.count, 'error') %> prohibited this interpreter from being saved:</h2>
      <ul>
        <% @interpreter.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render partial: 'interpreter_form', locals: {form: f} %>

  <div class="row">
    <div class="large-12 columns">
      <%= f.submit class: 'button tiny' %>
      <a href="#" data-reveal-id="interpreterDelete" class="button tiny alert right">Delete</a>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="large-12 columns">
    <%= render partial: 'help_interpreter' %><br>
  </div>
</div>

<div class="row">
  <div class="large-12 columns" id="accordion-refresh">
    <dl class="accordion" data-accordion="functions_accordion">
      <dd>
        <% content_id_name = '_function_content' %>
        <a href="#newpart" onclick="editorRubyAccordion('<%= content_id_name %>')">New function</a>
        <div id="newpart" class="content">
          <%= render partial: 'function_form',
                     locals: {link: [@interpreter, @interpreter.functions.build], new: true} %>
        </div>
      </dd>

      <% @functions.each_with_index do |f, index| %>
        <a name="<%= f.id %>"></a>
        <dd>
          <a href="#part<%= f.id %>" onclick="editorRubyAccordion('<%=f.id.to_s+content_id_name  %>')"><%=(index+1).to_s+' '+f.title %></a>
          <div id="part<%= f.id %>" class="content <%= 'active' if params[:function_id]==f.id.to_s %>">

            <% if params[:function_id]==f.id.to_s %>
              <% content_for :javascripts do %>
                <script>
                  editorRubyAccordion('<%=f.id.to_s+content_id_name %>');
                  window.location.hash="<%= f.id %>";
                </script>
              <% end %>
            <% end %>

            <%= render partial: 'function_form',
                       locals: {link: [@interpreter, f],new: false} %>
          </div>
        </dd>
      <% end %>
    </dl>
  </div>
</div>

app/views/interpreters/new.html.erb
<%= breadcrumbs({title: 'creator page', link: creator_path}, current: 'new interpreter') %>
<%= tinymce_assets %>
<%= tinymce %>

<% if @interpreter.errors.any? %>
  <div class="alert-box alert">
    <%= pluralize(@interpreter.errors.count, 'error') %> :<br>
    <a href="#" class="close">&times;</a>

    <ul>
      <% @interpreter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for :interpreter, url: interpreters_path do |f| %>

  <%= render partial: 'interpreter_form', locals: {form: f} %>

  <div class="row">
    <div class="large-12 columns">
      <%= f.submit 'save', class: 'button small' %>
    </div>
  </div>
<% end %>

app/views/interpreters/show.html.erb
<%= breadcrumbs(current: @interpreter.title) %>
<div class="row">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-4 columns">
        <h4><%= @interpreter.title %></h4>
        <% if @interpreter.is_finish %>
          Is finished
        <% else %>
          Is not finished
        <% end %>
      </div>
      <div class="large-6 columns">
        <h4><%= @interpreter.description.html_safe %></h4>
      </div>
      <div class="large-2 columns">
        <% if current_user == @interpreter.user || admin? %>
          <div class="text-right">
            <%= link_to 'Edit', edit_interpreter_path(@interpreter), class: 'edit-button-expand-tiny', method: :get %>
          </div>
        <% end %>

        <!--grade section-->
        <%= render partial: 'page/grade', locals: {
            grade_link: [@interpreter,@interpreter.interpreter_grades.build],
            grade_value: @grade
        }%>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-2 text-center columns">
    <h4>All function</h4>
    <% @functions.each_with_index do |f, index| %>
      <div class="columns">
        <%= link_to f.name, interpreter_function_path(@interpreter,f), class: 'button small round expand' %>
      </div>
    <% end %>
  </div>
  <div class="large-10 columns">
    <%= render partial: 'page/add_comment', locals: {link: [@interpreter,@interpreter.interpreter_comments.build]} %>
    <br>

    <!--Comments zone-->
    <%= will_paginate @comments, renderer: FoundationPagination::Rails %>
    <% @comments.each do |c| %>
      <div class="row comment-panel">

        <!-- Content zone-->
        <%= render partial: 'page/comment_content', locals: {comment: c} %>

        <!-- +/- zone, vote of comments-->
        <div class="large-2 columns text-right">
          <%= render partial: 'page/comment_vote', locals: {
              votes: c.interpreter_comment_votes,
              update_vote_link: [@interpreter,c],
              create_vote_link: [@interpreter,c,c.interpreter_comment_votes.build]
          } %>
        </div>
      </div>
    <% end %><br>
    <%= will_paginate @comments, renderer: FoundationPagination::Rails %>
  </div>
</div>