config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/:id' => 'users#show', as: 'user'
  match 'users/:id' => 'users#destroy', via: :delete, as: :admin_destroy_user
  match 'users/:id/rise_to_admin' => 'users#rise_to_admin', via: :get, as: :rise_to_admin_user
  get 'users', to: 'users#index'

  resources :tutorials do
    resources :tutorial_grades, only: [:create]
    resources :tutorial_comments, path: 'comments', only: [:create,:update,:destroy] do
      resources :tutorial_comment_votes, only: [:create,:update,:destroy]
    end
    resources :parts do
      get 'up_position', on: :member
      get 'down_position', on: :member
      get 'execute', on: :member
      resources :part_votes,only: [:create,:update,:destroy]
      resources :done_parts,only: [:create,:destroy]
      resources :part_comments, path: 'comments', only: [:index,:create,:update,:destroy] do
        resources :part_comment_votes, only: [:create,:update,:destroy]
      end
    end
  end

  resources :interpreters do
    resources :interpreter_grades, only: [:create]
    resources :interpreter_comments, path: 'comments', only: [:create,:update,:destroy] do
      resources :interpreter_comment_votes, only: [:create,:update,:destroy]
    end
    resources :functions do
      get 'up_position', on: :member
      get 'down_position', on: :member
      resources :function_votes,only: [:create,:update,:destroy]
      resources :function_comments, path: 'comments', only: [:index,:create,:update,:destroy] do
        resources :function_comment_votes, only: [:create,:update,:destroy]
      end
    end
  end

  get '/home' => 'page#home'
  get '/creator' => 'page#creator'
  get '/about' => 'page#about'

  root 'page#home'

end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  has_many :tutorial_comments, inverse_of: :tutorial, dependent: :delete_all
  has_many :tutorial_grades, inverse_of: :tutorial, dependent: :delete_all
  has_many :parts, inverse_of: :tutorial, dependent: :delete_all
  belongs_to :user
  belongs_to :interpreter

  validates :title, :description, :user, :interpreter, presence: true
  validates :is_finish, :inclusion => {:in => [true, false]}

  def grade_mean
    return 0.0 if self.tutorial_grades.count == 0
    self.tutorial_grades.sum(:grade) / self.tutorial_grades.count
  end

  def parts_ordered
    self.parts.order(position: :asc)
  end

  def done(user)
    parts = self.parts
    count = 0
    finished = true
    parts.each do |p|
      count += 1
      finished = false unless user.done_parts.exists?(part_id: p.id)
    end
    return nil if count == 0
    finished
  end

  def comments_top
    self.tutorial_comments.sort_by{|e| e.votes.where(positive: false).count-e.votes.where(positive: true).count}
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :authenticate_creator!, except: [:show,:new,:create]
  before_action :authenticate_user!, only: [:new,:create]

  def show
    @tutorial = Tutorial.find(params[:id])
    @grade = @tutorial.tutorial_grades.where(user_id: current_user.id).first.grade rescue nil
    @grade = 0.0 if @grade.blank?
    @comments = @tutorial.comments_top.paginate(page: params[:page], per_page: COMMENTS_PER_PAGE)
  end

  def new
    @tutorial = Tutorial.new
  end

  def create
    @tutorial = Tutorial.new(tutorial_params)

    @tutorial.user = current_user
    @tutorial.is_finish = true
    @tutorial.version = 1
    if @tutorial.save
      redirect_to edit_tutorial_path(@tutorial)
    else
      render 'new'
    end
  end

  def edit
    @tutorial = Tutorial.find params[:id]
    @parts = @tutorial.parts_ordered
    @part = Part.new
  end

  def update
    @tutorial = Tutorial.find(params[:id])

    @tutorial.version = @tutorial.version+1

    if @tutorial.update(tutorial_params)
      redirect_to edit_tutorial_path(@tutorial)
    else
      render 'edit'
    end
  end

  def destroy
    Tutorial.find(params[:id]).destroy
    redirect_to root_path, flash: { info: 'Tutorial deleted' }
  end

  private
  def authenticate_creator!
    tutorial = Tutorial.find(params[:id])
    redirect_to root_path unless tutorial.user == current_user || admin?
  end

  def tutorial_params
    params.require(:tutorial).permit(:title, :description, :is_finish, :interpreter_id, :tutorial_comment_id, :version)
  end
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/tutorials/_part_form.html.erb
<%= form_for link do |f| %>
  <div class="row">
    <% if new %>
      <div class="large-12 columns">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
    <% else %>
      <div class="large-1 text-center columns">
        <%= link_to '', up_position_tutorial_part_path(link.first, id: link.last.id.to_s),class: 'arrow-up', method: :get %><br><br>
        <%= link_to '', down_position_tutorial_part_path(link.first, id: link.last.id.to_s),class: 'arrow-down', method: :get %>
      </div>
      <div class="large-11 columns">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>

    <% end %>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <%= f.label :content %>
      <%= f.text_area :content, namespace: link.last.id, class: 'tinymce', rows: 15 %>
    </div>
  </div>
  <div class="row">
    <div class="large-<%= new ? '12' : '6' %> columns">
      <%= f.label :signature %>
      <%= f.text_area :signature, namespace: link.last.id %>
    </div>
    <% unless new %>
      <div class="large-6 columns">
        <%= label_tag :signature_tester %>
        <% if !params[:output].blank? && params[:part_id] == link.last.id.to_s %>
          <%= text_area_tag :signature_tester, link.last.id.to_s==params[:part_id]?params[:output]:'', readonly: true, size: "10x10" %>
        <% end %>
        <%= link_to "Execute", execute_tutorial_part_path(link.first, id: link.last.id.to_s), class: 'button tiny' %>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="large-6 columns">
      <%= f.submit class: 'button tiny' %>
      <% unless new %>
        <%= link_to 'delete', link, method: :delete, class: 'button tiny alert right' %>
        <%= link_to 'Go to the page', link, class: 'button tiny right' %>
      <% end %>
    </div>
    <div class="large-6 columns">
    </div>
  </div>
<% end %>

app/views/tutorials/_tutorial.html.erb
<p>
  title : <%= tutorial.title %> V <%= tutorial.version %><br>
  description : <%= tutorial.description %><br>
  is finish ? : <%= tutorial.is_finish %>
</p>

app/views/tutorials/edit.html.erb
<%= breadcrumbs({title: @tutorial.title,link: @tutorial},current: 'edit') %>
<%= tinymce_assets %>

<%= form_for :tutorial, url: tutorial_path(@tutorial), method: :patch do |f| %>
  <% if @tutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutorial.errors.count, 'error') %> prohibited this interpreter from being saved:</h2>
      <ul>
        <% @tutorial.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= render partial: 'layouts/delete_confirm', locals: {id: 'tutorialDelete', name: 'tutorial', link: @tutorial}%>
  <div class="row">
    <div class="large-12 columns">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'tinymce', rows: 15 %>
      <%= tinymce %>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns"><br>
      <%= f.label :interpreter %>
      <%= f.collection_select :interpreter_id, Interpreter.all, :id, :title %>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns"><br>
      <%= f.label :is_finish %>
      <%= f.check_box :is_finish %>
    </div>
  </div>

  <div class="row">
    <div class="large-2 columns">
      <%= f.submit 'save', class: 'button tiny expand' %>
    </div>
    <div class="large-2 columns">
      <a href="#" data-reveal-id="tutorialDelete" class="button tiny alert right expand">Delete</a>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="large-12 columns">
    <dl class="accordion" data-accordion>
      <dd>
        <% signature_id_name = 'part_signature' %>
        <a href="<%= request.original_url %>#newpart" onclick="editorNoRubyAccordion('<%= signature_id_name %>')">New part</a>
        <div id="newpart" class="content">
          <%= render partial: 'part_form',
                     locals: {link: [@tutorial, @tutorial.parts.build], new: true} %>
        </div>
      </dd>

      <% @parts.each_with_index do |p, index| %>
        <a name="<%= p.id %>"></a>
        <dd>
          <a href="#part<%= p.id %>" onclick="editorNoRubyAccordion('<%= p.id.to_s+'_'+signature_id_name %>')"><%= (index+1).to_s+' '+p.title %></a>
          <div id="part<%= p.id %>" class="content <%= 'active' if params[:part_id]==p.id.to_s %>">

            <% if params[:part_id]==p.id.to_s %>
              <% content_for :javascripts do %>
                <script>
                  editorNoRubyAccordion('<%= p.id.to_s+'_'+signature_id_name %>');
                  window.location.hash="<%= p.id %>";
                </script>
              <% end %>
            <% end %>

            <%= render partial: 'part_form',
                       locals: {link: [@tutorial, p], new: false} %>
          </div>
        </dd>
      <% end %>
    </dl>
  </div>
</div>

app/views/tutorials/new.html.erb
<%= breadcrumbs({title: 'creator page', link: creator_path}, current: 'new tutorial') %>
<%= tinymce_assets %>
<%= tinymce %>

<% if @tutorial.errors.any? %>
  <div class="alert-box alert">
    <%= pluralize(@tutorial.errors.count, 'error') %> :<br>
    <a href="#" class="close">&times;</a>

    <ul>
      <% @tutorial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for :tutorial, url: tutorials_path do |f| %>
  <div class="row">
    <div class="large-12 columns">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'tinymce', rows: 15 %>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <br/>
      <%= f.label :interpreter %>
      <%= f.collection_select :interpreter_id, Interpreter.all, :id, :title %>
    </div>
  </div>

  <div class="row">
    <div class="large-6 large-centered columns">
      <br/><%= f.submit 'save', class: 'button small expand' %>
    </div>
  </div>
<% end %>

app/views/tutorials/show.html.erb
<%= breadcrumbs(current: @tutorial.title) %>
<div class="row">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-4 columns">
        <h4><%= @tutorial.title %></h4>
        <% if @tutorial.is_finish.yesno.downcase %>
          <p>Is finished</p>
        <% else %>
          <p>Is not finished</p>
        <% end %>
      </div>
      <div class="large-6 columns">
        <h4><%= @tutorial.description.html_safe %></h4>
      </div>
      <div class="large-2 columns">
        <% if @tutorial.user == current_user || admin? %>
          <div class="text-right">
            <%= link_to 'Edit', edit_tutorial_path(@tutorial), class: 'edit-button-expand-tiny round', method: :get  %>
          </div>
        <% end %>

        <!--grade section-->
        <%= render partial: 'page/grade', locals: {
            grade_link: [@tutorial,@tutorial.tutorial_grades.build],
            grade_value: @grade.to_f
        }%>

      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-12 columns text-center">
    <%= link_to 'Start', [@tutorial,@tutorial.parts_ordered.first], class: 'button small' %>
  </div>
</div>

<div class="row">

  <!--Tutorial parts zone-->
  <div class="large-2 columns">
    <%= render partial: 'parts/parts',
               locals: {parts: @tutorial.parts_ordered,
                        tutorial: @tutorial,
                        user: current_user}  %>
  </div>

  <!--New comment zone-->
  <div class="large-10 columns">

    <%= render partial: 'page/add_comment', locals: {link: [@tutorial,@tutorial.tutorial_comments.build]} %>
    <br>

    <!--Comments zone-->
    <%= will_paginate @comments, renderer: FoundationPagination::Rails %>
    <% @comments.each do |c| %>
      <div class="row comment-panel">

        <!-- Content zone-->
        <%= render partial: 'page/comment_content', locals: {comment: c} %>

        <!-- +/- zone, vote of comments-->
        <div class="large-2 columns text-right">
          <%= render partial: 'page/comment_vote', locals: {
              votes: c.tutorial_comment_votes,
              update_vote_link: [@tutorial,c],
              create_vote_link: [@tutorial,c,c.tutorial_comment_votes.build]
          } %>
        </div>
      </div>
    <% end %><br>
    <%= will_paginate @comments, renderer: FoundationPagination::Rails %>
  </div>
</div>