config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/:id' => 'users#show', as: 'user'
  match 'users/:id' => 'users#destroy', via: :delete, as: :admin_destroy_user
  match 'users/:id/rise_to_admin' => 'users#rise_to_admin', via: :get, as: :rise_to_admin_user
  get 'users', to: 'users#index'

  resources :tutorials do
    resources :tutorial_grades, only: [:create]
    resources :tutorial_comments, path: 'comments', only: [:create,:update,:destroy] do
      resources :tutorial_comment_votes, only: [:create,:update,:destroy]
    end
    resources :parts do
      get 'up_position', on: :member
      get 'down_position', on: :member
      get 'execute', on: :member
      resources :part_votes,only: [:create,:update,:destroy]
      resources :done_parts,only: [:create,:destroy]
      resources :part_comments, path: 'comments', only: [:index,:create,:update,:destroy] do
        resources :part_comment_votes, only: [:create,:update,:destroy]
      end
    end
  end

  resources :interpreters do
    resources :interpreter_grades, only: [:create]
    resources :interpreter_comments, path: 'comments', only: [:create,:update,:destroy] do
      resources :interpreter_comment_votes, only: [:create,:update,:destroy]
    end
    resources :functions do
      get 'up_position', on: :member
      get 'down_position', on: :member
      resources :function_votes,only: [:create,:update,:destroy]
      resources :function_comments, path: 'comments', only: [:index,:create,:update,:destroy] do
        resources :function_comment_votes, only: [:create,:update,:destroy]
      end
    end
  end

  get '/home' => 'page#home'
  get '/creator' => 'page#creator'
  get '/about' => 'page#about'

  root 'page#home'

end

app/views/page/_add_comment.html.erb
<% if user_signed_in? %>
  <h4>Comments</h4>
  <%= form_for(link) do |f| %>
    <div class="row">
      <div class="large-12 columns">
        <%= f.text_area  :content, placeholder: 'New comment' %>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns text-right">
        <%= f.submit 'add comment', class: 'button tiny'%>
      </div>
    </div>
  <% end %>
<% end %>

app/views/page/_comment_content.html.erb
<div class="large-10 columns">
  <%= link_to comment.user.username, comment.user %> <span class="right"><%= comment.created_at.strftime("Posted on %d %a %Y at %T") %></span><br><br>
  <%= comment.content %>
  <% if current_user.try(:admin) == true %>
    <div class="large-2">
      <br><br>
      <% id = "part_com"+comment.id.to_s %>
      <a data-reveal-id="<%= id %>" class="button tiny alert right expand">Delete</a>
      <%= render partial: 'layouts/delete_confirm', locals: {id: id, name: 'comment', link: comment.path+[comment]} %>
    </div>
  <% end %>
</div>

app/views/page/_comment_vote.html.erb
<!--Project: Learn-it-->
<!--Author : Etienne Frank-->
<!--Year   : 2014-->

<!--Vote section-->

<% return unless user_signed_in? %>

<!--If the vote exist, we have only to update it-->
<% @exist = false %>
<% votes.each do |v| %>
  <% if !v.user.nil? && v.user.id == current_user.id %>
    <% @exist = true %>

    <% if v.positive==true %>
      <%= nb_pos_vote(votes) %>
      <span data-tooltip class="tip-right" title="Already vote this choice !">
        <button class="plus-button-disabled"><i class="fi-plus"></i></button>
      </span>
      <%= form_for(update_vote_link+[v]) do |f| %>
          <%= f.hidden_field :positive, :value => false %>
          <%= hidden_field_tag :page, params[:page] %>
          <%= nb_neg_vote(votes)-1 %>
          <button type="submit" class="minus-button"><i class="fi-minus"></i></button>
      <% end %>
    <% else %>
      <%= form_for(update_vote_link+[v]) do |f| %>
        <%= f.hidden_field :positive, :value => true %>
        <%= hidden_field_tag :page, params[:page] %>
        <%= nb_pos_vote(votes) %>
          <button type="submit" class="plus-button"><i class="fi-plus"></i></button>
      <% end %>
      <%= nb_neg_vote(votes)-1 %>
      <span data-tooltip class="tip-right" title="Already vote this choice !">
        <button class="minus-button-disabled"><i class="fi-minus"></i></button>
      </span>
    <% end %>
    <% break %>
  <% end %>
<% end %>

<!--If the the user haven't vote yet, we have to create it-->
<% if @exist == false %>
  <%= form_for(create_vote_link) do |f| %>
    <%= f.hidden_field :positive, :value => true %>
    <%= hidden_field_tag :page, params[:page] %>
    <%= nb_pos_vote(votes) %>
    <button type="submit" class="plus-button"><i class="fi-plus"></i></button>
  <% end %>
  <%= form_for(create_vote_link) do |f| %>
    <%= f.hidden_field :positive, :value => false %>
    <%= hidden_field_tag :page, params[:page] %>
    <%= nb_neg_vote(votes)-1 %>
    <button type="submit" class="minus-button"><i class="fi-minus"></i></button>
  <% end %>
<% end %>

app/views/page/_grade.html.erb
<% if user_signed_in? %>
  <%= form_for(grade_link) do |f| %>
    <%= f.label :grade do %>
      Grade (1 to 10)
    <% end %>
    <%= f.number_field(:grade, in: 1.0..10.0, step: 0.1, value: grade_value) %>
    <div class="text-right">
      <%= f.submit 'Set grade', class: 'button tiny expand' %>
    </div>
  <% end %>
<% else %>
  Grade<br>
  <input type="text" disabled value="<%= grade_value %>"/>
<% end %>

app/views/page/_tutorial.html.erb
<div class="row">
  <a href="<%= url_for(tutorial) %>" class="button round expand">
    <%= tutorial.title %> <br>
    Ver.<%= tutorial.version %> <br>
    Grade : <%= tutorial.grade_mean %>
  </a>
</div>

app/views/page/about.html.erb
<%= breadcrumbs current: 'about' %>
<div class="text-center">
  <h3>Weclome</h3>
  <h5>
    This is a programming learning site web.<br>
    You will find tutorials, which you can do it right now !<br>
    You can also make your own tutorial !<br>
    All tutorials use interpreters.<br>
    Those interpreters can be create by the community or by you.<br>
  </h5>
  <br><br>
  <h5>
    This is a Bachelor project for the school : <a href="http://www.he-arc.ch/">HE-ARC</a><br>
    Student : <a href="https://github.com/ice-blaze">E. Frank</a><br>
    Professor : A. Rizzotti
  </h5>
</div>

app/views/page/creator.html.erb
<%= breadcrumbs current: 'creator' %>

<div class="row">
  <div class="large-12 column text-center">
    <p>
      Before creating a new interpreter or tutorial, look if it already exist.<br>
      Use an interpreter which exist or try to improve others tutorial with rich commentaries
    </p>
  </div>
</div>

<div class="row">
  <div class="large-6 column text-center">
    <%= button_to 'Create tutorials', new_tutorial_path, class: 'button', method: :get  %>
  </div>
  <div class="large-6 column text-center">
    <%= button_to 'Create interpreter', new_interpreter_path, class: 'button', method: :get %>
  </div>
</div>

<div class="row">
  <div class="large-6 column">
    <%= form_tag(creator_path, method: 'get', id: 'search-tutorial-form') do %>
      <%= text_field_tag :tutorial_search, params[:tutorial_search], placeholder: 'Search tutorial' %>
      <%= hidden_field_tag :interpreter_search, params[:interpreter_search] %>
      <div class="text-center">
        <%= submit_tag 'Search', name: nil, class: 'button tiny' %>
      </div>
    <% end %>
  </div>
  <div class="large-6 column">
    <%= form_tag(creator_path, method: 'get', id: 'search-interpreter-form') do %>
      <%= text_field_tag :interpreter_search, params[:interpreter_search], placeholder: 'Search interpreter' %>
      <%= hidden_field_tag :tutorial_search, params[:tutorial_search] %>
      <div class="text-center">
        <%= submit_tag 'Search', name: nil, class: 'button tiny' %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="large-6 column">
    <% @tutorials.each_with_index do |t, index| %>
      <%= render partial: 'tutorial', locals: {index: index, tutorial: t}  %>
    <% end %>
    <%= will_paginate @tutorials, param_name: 'tutorial_page', renderer: FoundationPagination::Rails %>
  </div>
  <div class="large-6 column">
    <% @interpreters.each_with_index do |t, index| %>
      <%= render partial: 'tutorial', locals: {index: index, tutorial: t}  %>
    <% end %>
    <%= will_paginate @tutorials, param_name: 'interpreter_page', renderer: FoundationPagination::Rails %>
  </div>
</div>

app/views/page/home.html.erb
<% title 'Home' %>

<%= breadcrumbs(current: 'home') %>

<% if cookies[:welcom_alert].blank? %>
  <div class="row">
    <div data-alert class="alert-box secondary large-8 large-offset-2 columns">
      <div class="text-center">
        <h3>Weclome</h3>
        <h5>
          This is a programming learning site web.<br>
          You will find tutorials, which you can do it right now !<br>
          You can also make your own tutorial !<br>
          All tutorials use interpreters.<br>
          Those interpreters can be create by the community or by you.<br>
        </h5>
      </div>
      <a href="#" class="close">&times;</a>
    </div>
  </div>
  <% cookies[:welcom_alert] = true %>
<% end %>

<div class="row">
  <div class="large-8 large-centered columns text-center">
    <%= form_tag(root_path, method: 'get', id: 'search-form') do %>
      <%= text_field_tag :search, params[:search], placeholder: 'Search tutorial' %>
      <%= submit_tag 'Search', name: nil, class: 'button tiny' %>
    <% end %>
  </div>
</div>

<div class="row">
  <% if @tutorials.blank? %>
    <div class="large-6 columns text-center">
      <h3>Top tutorials</h3>
      <div class="panel">
        <% @tops.each_with_index do |t, index| %>
          <%= render partial: 'tutorial', locals: {index: index, tutorial: t}  %>
        <% end %>
        <%= will_paginate @tops, param_name: 'top_page', renderer: FoundationPagination::Rails %>
      </div>
    </div>

    <div class="large-6 columns text-center">
      <h3>Most recent tutorial</h3>
      <div class="panel">
        <% @newest.each_with_index do |t, index| %>
          <%= render partial: 'tutorial', locals: {index: index, tutorial: t}  %>
        <% end %>
        <%= will_paginate @newest, param_name: 'recent_page', renderer: FoundationPagination::Rails %>
      </div>
    </div>
  <% else %>
    <div class="large-12 columns text-center">
      <h3>Search result</h3>
      <div class="panel">
        <% @tutorials.each_with_index do |t, index| %>
          <%= render partial: 'tutorial', locals: {index: index, tutorial: t}  %>
        <% end %>
        <%= will_paginate @tutorials, param_name: 'search_page', renderer: FoundationPagination::Rails %>
      </div>
    </div>
  <% end %>
</div>