config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/:id' => 'users#show', as: 'user'
  match 'users/:id' => 'users#destroy', via: :delete, as: :admin_destroy_user
  match 'users/:id/rise_to_admin' => 'users#rise_to_admin', via: :get, as: :rise_to_admin_user
  get 'users', to: 'users#index'

  resources :tutorials do
    resources :tutorial_grades, only: [:create]
    resources :tutorial_comments, path: 'comments', only: [:create,:update,:destroy] do
      resources :tutorial_comment_votes, only: [:create,:update,:destroy]
    end
    resources :parts do
      get 'up_position', on: :member
      get 'down_position', on: :member
      get 'execute', on: :member
      resources :part_votes,only: [:create,:update,:destroy]
      resources :done_parts,only: [:create,:destroy]
      resources :part_comments, path: 'comments', only: [:index,:create,:update,:destroy] do
        resources :part_comment_votes, only: [:create,:update,:destroy]
      end
    end
  end

  resources :interpreters do
    resources :interpreter_grades, only: [:create]
    resources :interpreter_comments, path: 'comments', only: [:create,:update,:destroy] do
      resources :interpreter_comment_votes, only: [:create,:update,:destroy]
    end
    resources :functions do
      get 'up_position', on: :member
      get 'down_position', on: :member
      resources :function_votes,only: [:create,:update,:destroy]
      resources :function_comments, path: 'comments', only: [:index,:create,:update,:destroy] do
        resources :function_comment_votes, only: [:create,:update,:destroy]
      end
    end
  end

  get '/home' => 'page#home'
  get '/creator' => 'page#creator'
  get '/about' => 'page#about'

  root 'page#home'

end

app/views/layouts/_delete_confirm.html.erb
<!--link / name / id-->

<div id="<%= id %>" class="reveal-modal" data-reveal>
  <h2>Do you really want to delete this <%= name %> ?</h2>
  <p>This action cannot be undone.</p>
  <a class="close-reveal-modal">&#215;</a>
  <%= link_to 'delete', link, method: :delete, class: 'button tiny alert right' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title)+' - Learn-it' : 'Learn-it' %></title>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="sticky">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1><a href="<%= root_path %>">Learn-it</a></h1>
          </li>
          <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>
        <section class="top-bar-section ">
        <% if user_signed_in? %>
          <ul class="left">
            <li><%= link_to 'Create tutorials',creator_path%></li>
          </ul>
          <ul class="right">
            <li><%= link_to current_user.username, current_user %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          </ul>
        <% else %>
          <ul class="right">
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
          </ul>
        <% end %>
        <% if current_user.try(:admin?) %>
            <ul class="left">
              <li><%= link_to 'Manage users', users_path %></li>
            </ul>
        <% end %>
          <ul class="left">
            <li><%= link_to 'About',about_path %></li>
          </ul>

        </section>
      </nav>
    </div>

    <div class="row small-6 large-centered columns">
      <% unless notice.nil? %>
        <!--<br>-->
        <!--<div data-alert class="notice alert-box info radius">-->
          <!--<% notice %>-->
          <!--<a href="#" class="close"> &times;</a>-->
        <!--</div>-->
      <% end %>

      <% unless alert.nil? %>
        <br>
        <div data-alert class="alert alert-box alert radius">
          <%= alert %>
          <a href="#" class="close">&times;</a>
        </div>
      <% end %>

      <% flash.each do |name, msg| -%>
        <br>
        <div data-alert class="alert alert-box alert radius">
          <%= content_tag :div, msg, class: name %>
          <a href="#" class="close">&times;</a>
        </div>
      <% end -%>
    </div>

    <div id="underdevelopment" class="reveal-modal" data-reveal>
      <h2>Under development</h2>
      <p class="lead">Under development</p>
      <p>Under development</p>
      <a class="close-reveal-modal">&#215;</a>
    </div>

    <%= yield %>


  </body>

  <%= javascript_include_tag 'application' %>

  <%= yield :javascripts %>
</html>